### ISSUE TITLE
Can you share pretrained weights?

### ISSUE THREAD

**Issue by prnvjb** [buiquangmanhhp1999/age_gender_estimation#2]
Hi,
Thanks for the implementation. Can you share the pretrained weights?

**Comment by buiquangmanhhp1999** [comment]
you can dowload weights file from https://drive.google.com/file/d/1wrvWlDVHt1gfgnglrTHrv_jWfk5ePVY2/view?usp=sharing.

**Comment by ACakshay** [comment]
Hi, Can you please share the updated link for weights file. TIA
